export default {
    // Common
    appName: 'إدارة',
    loading: 'جاري التحميل...',
    error: 'حدث خطأ',
    retry: 'إعادة المحاولة',
    cancel: 'إلغاء',
    save: 'حفظ',
    delete: 'حذف',
    search: 'بحث',
    noResults: 'لا توجد نتائج',
    ok: 'موافق',
    yes: 'نعم',
    no: 'لا',
    available: 'متاح',

    // Auth
    login: 'تسجيل الدخول',
    register: 'تسجيل جديد',
    logout: 'تسجيل الخروج',
    employeeId: 'رقم الموظف',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    loginSuccess: 'تم تسجيل الدخول بنجاح',
    registerSuccess: 'تم التسجيل بنجاح. حسابك قيد المراجعة',
    logoutSuccess: 'تم تسجيل الخروج بنجاح',
    invalidCredentials: 'رقم الموظف أو كلمة المرور غير صحيحة',
    accountInactive: 'حسابك غير مفعل. يرجى انتظار موافقة الإدارة',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب بالفعل؟',

    // Validation Messages
    fillAllFields: 'يرجى ملء جميع الحقول',
    passwordMinLength: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    registrationError: 'حدث خطأ أثناء التسجيل',

    // Navigation
    home: 'الرئيسية',
    events: 'الفعاليات',
    deals: 'العروض',
    news: 'الأخبار',
    profile: 'الملف الشخصي',
    notifications: 'الإشعارات',
    settings: 'الإعدادات',
    language: 'اللغة',
    about: 'عن التطبيق',
    help: 'المساعدة',
    chatbot: 'المساعد الذكي',
    user: 'مستخدم',

    // Chatbot
    chatbotWelcome: 'مرحباً! أنا المساعد الذكي لتطبيق إدارة. كيف يمكنني مساعدتك اليوم؟',
    chatbotOnline: 'متصل الآن',
    chatbotPlaceholder: 'اكتب رسالتك هنا...',
    chatbotEventsResponse: 'يمكنك الاطلاع على جميع الفعاليات المتاحة من خلال تبويب "الفعاليات". يمكنك التسجيل في أي فعالية تهمك!',
    chatbotDealsResponse: 'لدينا العديد من العروض الحصرية للموظفين! تفضل بزيارة تبويب "العروض" لمشاهدة جميع العروض المتاحة.',
    chatbotNewsResponse: 'يمكنك متابعة آخر الأخبار والإعلانات من خلال تبويب "الأخبار". نقوم بتحديث الأخبار بشكل مستمر.',
    chatbotHelpResponse: 'يسعدني مساعدتك! يمكنك سؤالي عن الفعاليات، العروض، الأخبار، أو أي شيء آخر متعلق بالتطبيق.',
    chatbotDefaultResponse: 'شكراً لرسالتك! يمكنني مساعدتك في معرفة المزيد عن الفعاليات، العروض، والأخبار. ما الذي تود معرفته؟',

    // Events
    eventDetails: 'تفاصيل الفعالية',
    registerForEvent: 'التسجيل في الفعالية',
    unregisterFromEvent: 'إلغاء التسجيل',
    registered: 'مسجل',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    location: 'الموقع',
    attendees: 'المشاركون',
    images: 'الصور',
    videos: 'الفيديوهات',
    registrationSuccess: 'تم التسجيل بنجاح',
    unregistrationSuccess: 'تم إلغاء التسجيل بنجاح',
    noEventsAvailable: 'لا توجد فعاليات متاحة حالياً',

    // News
    newsDetails: 'تفاصيل الخبر',
    publishDate: 'تاريخ النشر',
    category: 'الفئة',
    views: 'المشاهدات',
    general: 'عام',
    attachments: 'المرفقات',
    document: 'مستند',

    // Deals
    dealDetails: 'تفاصيل العرض',
    discount: 'خصم',
    freeItem: 'عنصر مجاني',
    expiresOn: 'ينتهي في',
    originalPrice: 'السعر الأصلي',
    dealType: 'نوع العرض',
    termsConditions: 'الشروط والأحكام',
    howToRedeem: 'كيفية الاستفادة',
    contactInfo: 'معلومات التواصل',
    useDeal: 'استخدام العرض',
    registered: 'مسجل',
    available: 'متاح',
    attendees: 'المشاركين',
    location: 'الموقع',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    myEvents: 'فعالياتي',
    allEvents: 'جميع الفعاليات',
    cannotUnregister: 'لا يمكن إلغاء التسجيل قبل ساعة واحدة من بداية الفعالية',
    registrationSuccess: 'تم التسجيل في الفعالية بنجاح',
    unregistrationSuccess: 'تم إلغاء التسجيل من الفعالية بنجاح',

    // Deals
    dealDetails: 'تفاصيل العرض',
    discount: 'خصم',
    expired: 'منتهي',
    termsConditions: 'الشروط والأحكام',
    howToRedeem: 'طريقة الاستخدام',
    originalPrice: 'السعر الأصلي',
    contactInfo: 'معلومات التواصل',
    noDealsAvailable: 'لا توجد عروض متاحة حالياً',

    // News
    newsDetails: 'تفاصيل الخبر',
    publishedAt: 'نشر في',
    noNewsAvailable: 'لا توجد أخبار متاحة حالياً',

    // Notifications
    markAsRead: 'تحديد كمقروء',
    markAllAsRead: 'تحديد الكل كمقروء',
    noNotifications: 'لا توجد إشعارات',
    deleteNotificationConfirm: 'هل أنت متأكد من حذف هذا الإشعار؟',

    // Profile
    editProfile: 'تعديل الملف الشخصي',
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح',
    passwordChanged: 'تم تغيير كلمة المرور بنجاح',
    uploadAvatar: 'تحميل صورة',
    deleteAvatar: 'حذف الصورة',
    logoutConfirm: 'هل أنت متأكد من تسجيل الخروج؟',
    changeAvatarSoon: 'قريباً... تغيير الصورة الشخصية',

    // Categories
    allCategories: 'جميع التصنيفات',
    training: 'تدريب',
    meeting: 'اجتماع',
    workshop: 'ورشة عمل',
    conference: 'مؤتمر',

    // Settings
    settings: 'الإعدادات',
    language: 'اللغة',
    arabic: 'العربية',
    english: 'English',

    // Status
    active: 'نشط',
    inactive: 'غير نشط',
    pending: 'في الانتظار',

    // Time
    now: 'الآن',
    hoursAgo: 'منذ {hours} ساعة',
    yesterday: 'أمس',

    // Profile Menu Items
    notificationsSettings: 'الإشعارات',
    notificationsSettingsDesc: 'إدارة إشعارات التطبيق',
    changePasswordDesc: 'تغيير كلمة المرور',
    helpSupport: 'المساعدة والدعم',
    helpSupportDesc: 'الحصول على المساعدة',
    logoutDesc: 'تسجيل الخروج من التطبيق',

    // Profile Stats
    registeredEvents: 'الفعاليات المسجلة',
    usedDeals: 'العروض المستخدمة',
    notificationsCount: 'الإشعارات',

    // Home Screen
    user: 'المستخدم',
    employee: 'موظف',
    employeeSystemDesc: 'موظف • نظام إدارة الموظفين',
    quickAccessTitle: 'الوصول السريع',
    appDescription: 'يمكنك من خلال هذا التطبيق متابعة الفعاليات، الاستفادة من العروض الحصرية، ومتابعة آخر الأخبار والإعلانات الخاصة بالشركة.',
    eventRegistration: 'تسجيل الحضور في الفعاليات',
    exclusiveDeals: 'عروض حصرية للموظفين',
    instantNotifications: 'إشعارات فورية',

    // Events Screen
    eventsTitle: 'الفعاليات',
    eventsAvailable: '{count} فعالية متاحة',
    noEvents: 'لا توجد فعاليات',
    noEventsInCategory: 'لم يتم العثور على فعاليات في هذه الفئة',

    // Deals Screen
    exclusiveDealsTitle: 'العروض الحصرية',
    dealsAvailable: '{count} عرض متاح',
    noDeals: 'لا توجد عروض',
    noDealsInCategory: 'لم يتم العثور على عروض في هذه الفئة',
    percentageDiscount: '{value}% خصم',
    fixedAmountDiscount: '{value} ج.م خصم',
    freeItem: 'مجاني',
    specialOffer: 'عرض خاص',
    expiredOffer: 'منتهي الصلاحية',
    expiredShort: 'منتهي',
    useOffer: 'استخدم العرض',

    // Login Screen
    appTitle: 'إدارة',
    systemTitle: 'نظام إدارة الموظفين',
    welcomeBackMsg: 'مرحباً بك مرة أخرى',
    systemForCompanies: 'نظام إدارة الموظفين للشركات العقارية',

    // News Details
    images: 'الصور',
    videos: 'الفيديوهات',
    attachments: 'المرفقات',

    // Messages
    languageChanged: 'تم تغيير اللغة بنجاح',
    restartRequired: 'قد تحتاج لإعادة تشغيل التطبيق لتطبيق التغييرات بالكامل',
    comingSoon: 'قريباً...',
    hello: 'مرحباً',
    welcomeBack: 'مرحباً بك مرة أخرى',
    quickAccess: 'الوصول السريع',
    personalInfo: 'المعلومات الشخصية',
    appVersion: 'الإصدار',
    employeeManagementSystem: 'نظام إدارة الموظفين',
    forPropertyCompanies: 'للشركات العقارية',
    versionInfo: 'الإصدار 1.0.0 • نظام إدارة الموظفين',
    
    // Additional translations
    or: 'أو',
    quickActions: 'الإجراءات السريعة',
    exploreFeatures: 'استكشف المميزات',
    eventManagement: 'إدارة الفعاليات',
    exclusiveDeals: 'عروض حصرية',
    instantNotifications: 'إشعارات فورية',
    discoverEvents: 'اكتشف الفعاليات الجديدة',
    loginToYourAccount: 'سجل دخولك إلى حسابك',
    createAccount: 'إنشاء حساب جديد',
    pleaseEnterCredentials: 'يرجى إدخال بيانات الدخول',
    loginFailed: 'فشل في تسجيل الدخول',
    
    // Profile translations
    eventsAttended: 'الفعاليات المحضورة',
    dealsUsed: 'العروض المستخدمة',
    newsRead: 'الأخبار المقروءة',
    enabled: 'مفعل',
    privacy: 'الخصوصية',
    help: 'المساعدة',
    changeLanguage: 'تغيير اللغة',
    selectLanguage: 'اختر اللغة',
    logoutConfirmation: 'هل أنت متأكد من تسجيل الخروج؟',
    personalInfo: 'المعلومات الشخصية',
    department: 'القسم',
    joinDate: 'تاريخ الانضمام',
    
    // Home screen translations
    welcome: 'مرحباً بك',
    exploreContent: 'استكشف المحتوى والفعاليات والعروض الحصرية',
    viewAll: 'عرض الكل',
    personalStats: 'الإحصائيات الشخصية',
    registeredEvents: 'الفعاليات المسجلة',
    usedDeals: 'العروض المستخدمة',
    thisWeekEvents: 'فعاليات هذا الأسبوع',
    upcomingEvents: 'الفعاليات القادمة',
    seeAll: 'عرض الكل',
    timeLeft: 'الوقت المتبقي',
    viewDetails: 'عرض التفاصيل',
    companyInfo: 'معلومات الشركة',
    propertyManagementCompany: 'شركة إدارة العقارات المتخصصة',
    employees: 'موظف',
    projects: 'مشروع',
    yearsExperience: 'سنوات خبرة',
    importantDates: 'المواعيد المهمة',
    confirmed: 'مؤكد',
    pending: 'في الانتظار',
    holiday: 'إجازة',
    noLocation: 'لم يتم تحديد الموقع',
    images: 'الصور',
    videos: 'الفيديوهات',
    latestNews: 'آخر الأخبار',
    views: 'مشاهدة',
    noNewsInCategory: 'لم يتم العثور على أخبار في هذه الفئة',
};